### ISSUE TITLE
F9 shortcut fails if triggered after window is closed but app not quit on macOS

### ISSUE THREAD

**Issue by 1j01** [1j01/tracky-mouse#8]
It gets an error in the main process because the window is destroyed. 
It should either unregister the shortcut when closing the app window, or the global shortcut handler should handle reopening the window when needed.
```
Uncaught Exception:
TypeError: Object has been destroyed
    at Function.<anonymous> (/Users/io/Projects/tracky-mouse/tracky-mouse-electron/src/electron-main.js:186:14)
```

![image](https://user-images.githubusercontent.com/3630663/184030801-216bd9d8-59ad-492f-8990-8ab8d211a07c.png)

**Comment by 1j01** [comment]
I'm also getting this on Windows, when closing the main window and then pressing F9.
I think the screen overlay window isn't closing and so the app is staying running?
```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError: Object has been destroyed
    at Function.<anonymous> (C:\Users\Isaiah\Projects\tracky-mouse\tracky-mouse-electron\src\electron-main.js:211:14)

[OK]
```
